export default function Home() {
  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px',
    }}>
      <div style={{
        backgroundColor: 'white',
        borderRadius: '12px',
        padding: '40px',
        maxWidth: '500px',
        textAlign: 'center',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
      }}>
        <h1 style={{ margin: '0 0 16px' }}>SavvyCal Quick Booker</h1>
        <p style={{ color: '#666', lineHeight: 1.6 }}>
          This service enables one-click booking for SavvyCal time slots.
        </p>
        <p style={{ color: '#999', fontSize: '14px', marginTop: '24px' }}>
          Links are generated by the Propose Times Raycast extension.
        </p>
      </div>
    </div>
  )
}
